# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mig/Desktop/junior-spring/graphics/assignments/traingle/dependencies/GLFW/CMake/modules/FindVulkan.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mig/Desktop/junior-spring/graphics/assignments/traingle/dependencies/GLFW/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mig/Desktop/junior-spring/graphics/assignments/traingle/dependencies/GLFW/cmake_uninstall.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mig/Desktop/junior-spring/graphics/assignments/traingle/dependencies/GLFW/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mig/Desktop/junior-spring/graphics/assignments/traingle/dependencies/GLFW/src/glfw3.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mig/Desktop/junior-spring/graphics/assignments/traingle/dependencies/GLFW/src/glfw3Config.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/mig/Desktop/junior-spring/graphics/assignments/traingle/dependencies/GLFW/src/glfw_config.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/BasicConfigVersion-SameMajorVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/CMakeConfigurableFile.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/CheckIncludeFile.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/CheckSymbolExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))

/Users/mig/Desktop/junior-spring/graphics/assignments/traingle/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -H/Users/mig/Desktop/junior-spring/graphics/assignments/traingle -B/Users/mig/Desktop/junior-spring/graphics/assignments/traingle
